// @ts-ignore
import PaletteStyles from "../styling/Palette.module.css";
import { useState } from "react";

/** SWATCH GENERATED BY {random, red, green, blue} */
const Swatch = (props: { hex: string }) => {
  const [copy, setCopy] = useState(false);

  /** *************************************************************************** */

  return (
    <div style={{ display: "flex", flexDirection: "column", padding: "15px" }}>
      {/** COLOURED BOX: copies hex on click */}

      <div
        className={PaletteStyles.swatchBox}
        style={{ background: props.hex }}
        onClick={() => {
          navigator.clipboard.writeText(props.hex);
          setCopy(true);
        }}
      />

      {/**HEX TEXT: copies hex on click */}

      <p
        className={PaletteStyles.swatchHex}
        onClick={() => {
          navigator.clipboard.writeText(props.hex);
          setCopy(true);
        }}
      >
        {props.hex}
      </p>

      {/** COPIED POPUP: informs user that hex code was successfully copied */}

      <div
        onTransitionEnd={() => setCopy(false)}
        style={{
          opacity: copy ? "1" : "0",
          transition: copy
            ? "width 0.5s, height 0.5s, opacity 0.5s 0.5s"
            : "width 0.5s 0.5s, height 0.5s 0.5s, opacity 0.5s",
          border: "3px solid black",
          background: "white",
          textAlign: "center",
          marginTop: "-10px",
        }}
      >
        Copied!
      </div>
    </div>
  );
};

export default Swatch;
